# Generated by Django 5.2.17 on 2026-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='education',
            name='category',
        ),
        migrations.RemoveField(
            model_name='education',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='education',
            name='education_image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='education_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='education_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='event_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='experience',
            name='event_owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
