# Generated by Django 5.2.17 on 2026-09-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_projects_remove_education_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='project_image_url',
            new_name='skill_image_url',
        ),
    ]
